# Generated by Django 5.0.6 on 2025-04-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tl_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
