# Generated by Django 5.0.6 on 2025-04-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tl_app', '0002_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfilemodel',
            name='file',
            field=models.FileField(upload_to='media/uploads/'),
        ),
    ]
