# Generated by Django 5.0.6 on 2025-04-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tl_app', '0003_alter_uploadedfilemodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfilemodel',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
