# Generated by Django 5.2 on 2025-04-15 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tl_app', '0004_alter_uploadedfilemodel_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
