# Generated by Django 5.2 on 2025-04-17 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tl_app', '0005_delete_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='post_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_code', models.CharField()),
                ('phno', models.IntegerField(unique=True)),
                ('chat_id', models.CharField(max_length=30, unique=True)),
                ('user_name', models.IntegerField(unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedFileModel',
        ),
        migrations.AddField(
            model_name='post_model',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='tl_app.user', to_field='user_name'),
        ),
    ]
