# Generated by Django 5.2 on 2025-04-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tl_app', '0006_post_model_user_delete_uploadedfilemodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cust_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phno',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='chat_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.DeleteModel(
            name='post_model',
        ),
    ]
