# Generated by Django 5.2 on 2025-04-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tl_app', '0007_remove_user_cust_code_remove_user_phno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
