# Generated by Django 5.2 on 2025-04-19 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tl_app', '0008_chat_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='chat_id',
            new_name='phno',
        ),
    ]
