"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-yf2=4@(dxrv7q#e82@umd#hxvn!30%q4c2jz34aiw83ivz^ju_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','0.0.0.0','5f81-150-129-103-135.ngrok-free.app','3676-150-129-103-135.ngrok-free.app','your-ngrok-subdomain.ngrok.io']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'tl_app',
    'corsheaders',
    'csp',
    'social_django',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    
]

CORS_ALLOW_ALL_ORIGINS = True 

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'tl_app','template')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/



# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'tl_app/static'),
]

keys={}

def loadkeys(file_path):
    with open(file_path,'r') as file:
        content=file.read().strip().split('\n\n')
        for entry in content:
            lines=entry.splitlines()
            key_name=lines[0].split(':')[0].strip()
            key_value='\n'.join(lines[1:]).strip()
            keys[key_name]=key_value
    return keys


TELEGRAM_BOT_TOKEN1 ='7073224449:AAFsOirg8-rvhNTZrOTTmjECxRJ2KAfUISA'
TELEGRAM_CHAT_ID = '6240994051'


DATA_UPLOAD_MAX_NUMBER_FILES = 250
DATA_UPLOAD_MAX_MEMORY_SIZE = 1048576000 # 100 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 1048576000
#github oAUTH

AUTHENTICATION_BACKENDS = (
    'social_core.backends.github.GithubOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

SOCIAL_AUTH_GITHUB_KEY = 'Ov23lipmntSrqvBTYQci'
SOCIAL_AUTH_GITHUB_SECRET = '71de1e5311e0d4ebceff964919ae5da3cac1087c'
SOCIAL_AUTH_GITHUB_REDIRECT_URI='http://127.0.0.1:8000/accounts/github/login'


#telegrm oAUth

X_FRAME_OPTIONS = 'ALLOW-FROM https://oauth.telegram.org'

# Content Security Policy Settings (django-csp 4.0+ format)
CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'default-src': ["'self'"],
        'script-src': [
            "'self'",
            "'unsafe-inline'",  # Try removing this later and replacing with nonce
            'https://telegram.org',
            'https://oauth.telegram.org'
        ],
        'frame-src': [
            'https://telegram.org',
            'https://oauth.telegram.org'
        ],
        'frame-ancestors': [
            "'self'",
            'https://oauth.telegram.org'
        ],
        'connect-src': [
            "'self'",
            'https://telegram.org',
            'https://oauth.telegram.org'
        ],
        'img-src': [
            "'self'",
            'data:',
            'https://telegram.org',
            'https://oauth.telegram.org'
        ]
    }
}
